# Start with a base image containing Java runtime
FROM openjdk:8-jdk-alpine

# Add Maintainer Info
MAINTAINER Satish Gadey <gadeysatishkumar@gmail.com>

# Add a volume pointing to /tmp
VOLUME /tmp

# Make port 9098 available to the world outside this container
EXPOSE 9098

# The application's jar file
ARG JAR_FILE=target/school-service-0.0.1-SNAPSHOT.jar

# Add the application's jar to the container
ADD ${JAR_FILE} school-service-demo.jar

# Run the jar file 
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/school-service-demo.jar"]

